# Generated by Django 3.2.18 on 2023-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('valor', models.FloatField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
